### PR TITLE
Prevent iFrame Injection

### PR DESCRIPTION
**Pull request by RedYetiDev**
This pull-request will prevent any/all forms of iFrame Injection within the Javadoc page.

> [!NOTE]
> While this is a security issue, due to the low-severity of it, I do not believe it needs to be kept confidential, and it can be publicly displayed as a Github Pull-Request.

### CODE REVIEW

**Comment by randallwhitman** [comment]
Thanks @RedYetiDev - would it do as well to regenerate the JavaDoc with a newer JDK?

**Comment by RedYetiDev** [comment]
Yes that will also work, but I figured that if you might not want to make that change, this will also serve as a fix

**Comment by randallwhitman** [comment]
ideally the javadoc would to up-to-date for v2 - https://github.com/Esri/spatial-framework-for-hadoop/releases/tag/v2.0.0

**Comment by RedYetiDev** [comment]
Should I close this PR?

**Comment by randallwhitman** [comment]
No, let's not close it now - we can review whether this first or javadoc update straightway - thanks.

**Comment by randallwhitman** [comment]
If you like, you can review that #193 achieves this objective.

**Comment by RedYetiDev** [comment]
Looks good! Would you like me to close this?

**Comment by randallwhitman** [comment]
Yes, if the objective is covered, let's close it - thanks.

**Pull request closed without merging**
